/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SsDiseaseList {
    }
}
declare global {
    interface HTMLSsDiseaseListElement extends Components.SsDiseaseList, HTMLStencilElement {
    }
    var HTMLSsDiseaseListElement: {
        prototype: HTMLSsDiseaseListElement;
        new (): HTMLSsDiseaseListElement;
    };
    interface HTMLElementTagNameMap {
        "ss-disease-list": HTMLSsDiseaseListElement;
    }
}
declare namespace LocalJSX {
    interface SsDiseaseList {
    }
    interface IntrinsicElements {
        "ss-disease-list": SsDiseaseList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ss-disease-list": LocalJSX.SsDiseaseList & JSXBase.HTMLAttributes<HTMLSsDiseaseListElement>;
        }
    }
}
